//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh_HeThongTrungTamTinHoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuanKhoaHoc
    {
        public string MaHV { get; set; }
        public string MaKH { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayBinhLuan { get; set; }
    
        public virtual HocVien HocVien { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
