//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh_HeThongTrungTamTinHoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_HocVien_LopHoc
    {
        public int id { get; set; }
        public string MaLH { get; set; }
        public string MaHV { get; set; }
        public Nullable<double> DiemKiemTraLan1 { get; set; }
        public Nullable<double> DiemKiemTraLan2 { get; set; }
        public Nullable<double> DiemKiemTraLan3 { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
        public int Sobuoivang { get; set; }
        public string KetQua { get; set; }
        public Nullable<bool> ChoPhepNhapDiem { get; set; }
    
        public virtual HocVien HocVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
    }
}
