//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh_HeThongTrungTamTinHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoaHoc()
        {
            this.BinhLuanKhoaHoc = new HashSet<BinhLuanKhoaHoc>();
            this.GiaoDichHocPhi = new HashSet<GiaoDichHocPhi>();
            this.LopHoc = new HashSet<LopHoc>();
        }
        public string MaKH { get; set; }
        [Required(ErrorMessage = "Tên khóa học không được để trống")]
        [StringLength(100, ErrorMessage = "Tên khóa học không được vượt quá 100 ký tự")]
        public string TenKH { get; set; }

        [Required(ErrorMessage = "Mô tả không được để trống")]
        public string MoTa { get; set; }
        public string Anh { get; set; }

        [Display(Name = "Ngày bắt đầu")]
        [Required(ErrorMessage = "Bạn phải nhập ngày bắt đầu")]
        public System.DateTime NgayBatDau { get; set; }

        [Display(Name = "Ngày kết thúc")]
        //[Required(ErrorMessage = "Bạn phải nhập ngày kết thúc")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập số buổi học")]
        public int Sobuoihoc { get; set; }

        [Required(ErrorMessage = "Bạn phải chọn chương trình học")]
        public string MaChuongTrinh { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "Học phí phải là số dương")]
        [Required(ErrorMessage = "Bạn phải nhập học phí")]
        public double HocPhi { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập loại khóa học")]
        [StringLength(50, ErrorMessage = "Loại khóa học không được vượt quá 50 ký tự")]
        public string LoaiKH { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuanKhoaHoc> BinhLuanKhoaHoc { get; set; }
        public virtual ChuongTrinhHoc ChuongTrinhHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichHocPhi> GiaoDichHocPhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHoc> LopHoc { get; set; }
    }
}
