//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh_HeThongTrungTamTinHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LichHoc
    {
        public string MaLichHoc { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập mã học viên ")]
        public string MaHV { get; set; }

        [Required(ErrorMessage = " Bạn phải nhập mã lớp học ")]
        public string MaLH { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập ngày học")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayHoc { get; set; }

        public bool DiemDanh { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập giờ bắt đầu ")]
        public System.TimeSpan GioBatDau { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập giờ kết thúc ")]
        public System.TimeSpan GioKetThuc { get; set; }

        public virtual HocVien HocVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
    }
}
