//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh_HeThongTrungTamTinHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.ChiTiet_HocVien_LopHoc = new HashSet<ChiTiet_HocVien_LopHoc>();
            this.GiaoDichHocPhi = new HashSet<GiaoDichHocPhi>();
            this.LichDay = new HashSet<LichDay>();
            this.LichHoc = new HashSet<LichHoc>();
        }

        public string MaLH { get; set; }
        [Required(ErrorMessage = " Bạn phải nhập tên lớp học ")]
        public string TenPhong { get; set; }

        [Required(ErrorMessage = " Bạn phải nhập mã khóa học ")]
        public string MaKH { get; set; }

        [Required(ErrorMessage = " Bạn phải nhập sỉ số lớp học ")]
        public int SiSo { get; set; }

        [Required(ErrorMessage = " Bạn phải nhập giờ bắt đầu lớp học ")]
        public System.TimeSpan GioBatDau { get; set; }

        [Required(ErrorMessage = " Bạn phải nhập giờ kết thúc lớp học ")]
        public System.TimeSpan GioKetThuc { get; set; }

        [Required(ErrorMessage = " Bạn phải nhập giáo viên ")]
        public string MaGV { get; set; }

        [Required(ErrorMessage = " Bạn phải nhập trạng thái ")]
        public bool TrangThai { get; set; }

        [Required(ErrorMessage = " Bạn phải chọn thứ trong tuần")]
        public string ThuHoc { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_HocVien_LopHoc> ChiTiet_HocVien_LopHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichHocPhi> GiaoDichHocPhi { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichDay> LichDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHoc> LichHoc { get; set; }
    }
}
